# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) 
  displayName: 'Building $(buildConfiguration)'



- task: DotNetCoreCLI@2
  displayName: 'Testing $(buildConfiguration)'
  inputs:
    command: test
    projects: '**/*Tests/*csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publishing $(buildConfiguration)'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Storing Build Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectoy)'
    ArtifactName: 'StaffProductService'
- task: AzureWebApp@1
  displayName: 'Deploying $(BuildConfiguration) to test environment'
  inputs:
    azureSubscription: 'My Azure Subscription'
    appName: 'StaffProductNew'
    appType: webApp
    package: $(System.ArtifactsDirectory)/**/*.zip
